GET http://hacker-news.firebaseio.com/v0/topstories.json?print=pretty
Accept: application/json

###
#POST http://hacker-news.firebaseio.com/v0/topstories.json?print=pretty
#
##GET http://hacker-news.firebaseio.com/v0/beststories



GET /api/v2/items?page=1&per_page=20 HTTP/1.1

###


GET https://qiita.com/api/v2/items

###

GET https://hacker-news.firebaseio.com/v0/items
###

GET https://hacker-news.firebaseio.com/v0/item/27279479

###

GET https://hacker-news.firebaseio.com/v0/maxitem.json?print=pretty
